---
title: "Analysis of multimodal condition"
output: pdf_document
---

This script uses data compiled by *analyseData.R*.

## Load libraries

```{r warning=FALSE, message=FALSE}
library(party)
```

```{r echo=F}
try(setwd("~/Documents/MPI/ViniciusMultimodal/multimodalCommunicationGame/experiment/analysis/R/"))
```

## Load data

```{r}
d = read.csv("../../data/Final_Turn_data.csv", stringsAsFactors = F)
d = d[d$modalityCondition == "multi",]
```

## Prepare variables

```{r}
# Relabel modalities
d[d$turnModalityType=="multi",]$turnModalityType = "M"
d[d$turnModalityType=="unimodal acoustic",]$turnModalityType = "A"
d[d$turnModalityType=="unimodal visual",]$turnModalityType = "V"

# Only need one record per trial
d2 = d[!duplicated(d$trialString),]

# get turn modality type for T1
x = tapply(d[d$turnType=="T1",]$turnModalityType, d[d$turnType=="T1",]$trialString,head,n=1)
d2$turnModality.T1 = x[d2$trialString]

# remove NAs
d2 = d2[!is.na(d2$turnModality.T1),]
# relevel
d2$turnModality.T1 = relevel(factor(as.character(d2$turnModality.T1)),"V")

# get turn modality type for T2
x = tapply(d[d$turnType=="T2",]$turnModalityType, d[d$turnType=="T2",]$trialString,head,n=1)
d2$turnModality.T2 = x[d2$trialString]
d2$turnModality.T2[is.na(d2$turnModality.T2)] = "n"
d2$turnModality.T2 = relevel(factor(d2$turnModality.T2),'n')

# get turn modality type for T3
x = tapply(d[d$turnType=="T3",]$turnModalityType, d[d$turnType=="T3",]$trialString,head,n=1)
d2$turnModality.T3 = x[d2$trialString]
d2$turnModality.T3[is.na(d2$turnModality.T3)] = "n"
d2$turnModality.T3 = relevel(factor(d2$turnModality.T3),'n')

```

Make game variable.

```{r}

d2$trialTotal = d2$trial + (d2$game * (max(d2$trial)+1))
# Convert to proportion of games played, so that estimates reflect change per game.
d2$trialTotal = d2$trialTotal / 16
# Center the trialTotal variable so intercept reflects after the first game
d2$trialTotal = d2$trialTotal - 1

d2$incorrect = !d2$correct

```

Scale trial length variable.

```{r}

d2$trialLength.logcenter = log(d2$trialLength)
d2$trialLength.logcenter = d2$trialLength.logcenter - mean(d2$trialLength.logcenter)
```

# Binary trees


```{r}
cx = ctree(turnModality.T1~ 
             factor(turnModality.T2)+
             factor(turnModality.T3) + 
             factor(condition) +
             game
           , data=d2)
plot(cx, terminal_panel = node_barplot(cx, id=F))

```
\newpage
```{r}
cxT3 = ctree(turnModality.T3~ 
             factor(turnModality.T2)+
             factor(turnModality.T1) + 
             factor(condition) +
             game
           , data=d2[d2$turnModality.T3!="n",])
plot(cxT3, terminal_panel = node_barplot(cxT3, id=F))

```
\newpage
```{r}
cx2 = ctree(turnModality.T1~ 
             factor(turnModality.T2)+
             factor(turnModality.T3) + 
             factor(condition) +
             game +
             factor(dyadNumber)
           , data=d2)
plot(cx2, terminal_panel = node_barplot(cx2, id=F))

```

Graphs are also written to results/graphs/cTree/

```{r echo=F, message=F, warning=F}
# Print to files
pdf("../../results/graphs/cTrees/cTree_PredictT1Modality.pdf", height=4)
plot(cx, terminal_panel = node_barplot(cx, id=F))
dev.off()

pdf("../../results/graphs/cTrees/cTree_PredictT3Modality.pdf", height=4)
plot(cxT3, terminal_panel = node_barplot(cxT3, id=F))
dev.off()

pdf("../../results/graphs/cTrees/cTree_PredictT1Modality_GraphB.pdf", width=12)
plot(cx2, terminal_panel = node_barplot(cx2, id=F))
dev.off()

```

